const TestConfig = {
  CONTENT_LANGUAGE_REAL : 'en-US',
  CONTENT_LANGUAGE_FAKE : 'asdasd',
  FAKE_USER_ID: 'usr_asdsadsadsa',
  FAKE_GROUP_ID: 'grp_asdsadsadsa',
  INVALID_FILE_PATH: 'invalidFileFound',
  VOICEIT_DRIVE_URL:'https://drive.voiceit.io/files/',
  ENROLLMENT_FILE_FACE_AND_VOICE: 'test-data/enrollmentBMyFaceAndVoice.m4a',
  ENROLLMENT_FILE_A_1 : 'test-data/enrollmentA1.wav',
  ENROLLMENT_FILE_A_2 : 'test-data/enrollmentA2.wav',
  ENROLLMENT_FILE_A_3 : 'test-data/enrollmentA3.wav',
  VERIFICATION_FILE_A_1 : 'test-data/verificationA1.wav',
  VERIFICATION_FILE_A_2 : 'test-data/enrollmentA4.wav',
  ENROLLMENT_FILE_C_1 : 'test-data/enrollmentC1.wav',
  ENROLLMENT_FILE_C_2 : 'test-data/enrollmentC2.wav',
  ENROLLMENT_FILE_C_3 : 'test-data/enrollmentC3.wav',
  ENROLLMENT_FILE_D_1 : 'test-data/enrollmentD1.m4a',
  ENROLLMENT_FILE_D_2 : 'test-data/enrollmentD2.m4a',
  ENROLLMENT_FILE_D_3 : 'test-data/enrollmentD3.m4a',
  VERIFICATION_FILE_D_1 : 'test-data/verificationD1.m4a',
  VIDEO_ENROLLMENT_FILE_B_1 : 'test-data/videoEnrollmentB1.mov',
  VIDEO_ENROLLMENT_FILE_B_2 : 'test-data/videoEnrollmentB2.mov',
  VIDEO_ENROLLMENT_FILE_B_3 : 'test-data/videoEnrollmentB3.mov',
  VIDEO_ENROLLMENT_FILE_A_1 : 'test-data/videoEnrollmentA1.mov',
  VIDEO_ENROLLMENT_FILE_A_2 : 'test-data/videoEnrollmentA2.mov',
  VIDEO_ENROLLMENT_FILE_A_3 : 'test-data/videoEnrollmentA3.mov',
  VIDEO_ENROLLMENT_FILE_D_1 : 'test-data/videoEnrollmentD1.mov',
  VIDEO_ENROLLMENT_FILE_D_2 : 'test-data/videoEnrollmentD2.mov',
  VIDEO_ENROLLMENT_FILE_D_3 : 'test-data/videoEnrollmentD3.mov',
  VIDEO_VERIFICATION_FILE_D_1 : 'test-data/videoVerificationD1.mov',
  VIDEO_VERIFICATION_FILE_B_1 : 'test-data/videoVerificationB1.mov',
  VIDEO_VERIFICATION_FILE_B_2 : 'test-data/videoVerificationB2.mp4',
  VIDEO_VERIFICATION_FILE_A_1 : 'test-data/videoVerificationA1.mov',
  VIDEO_ENROLLMENT_FILE_C_1 : 'test-data/videoEnrollmentC1.mov',
  VIDEO_ENROLLMENT_FILE_C_2 : 'test-data/videoEnrollmentC2.mov',
  VIDEO_ENROLLMENT_FILE_C_3 : 'test-data/videoEnrollmentC3.mov',
  FACE_ENROLLMENT_FILE_B_1 : 'test-data/faceEnrollmentB1.mp4',
  FACE_ENROLLMENT_FILE_B_2 : 'test-data/faceEnrollmentB2.mp4',
  FACE_ENROLLMENT_FILE_B_3 : 'test-data/faceEnrollmentB3.mp4',
  FACE_ENROLLMENT_FILE_A_1 : 'test-data/faceEnrollmentA1.mov',
  FACE_ENROLLMENT_FILE_A_2 : 'test-data/faceEnrollmentA2.mov',
  FACE_ENROLLMENT_FILE_A_3 : 'test-data/faceEnrollmentA3.mov',
  FACE_VERIFICATION_FILE_B_1 : 'test-data/faceVerificationB1.mp4',
  FACE_VERIFICATION_FILE_C_1 : 'test-data/faceVerificationC1.mp4',
  ENGLISH_PHRASE : 'Never forget tomorrow is a new day',
  ENGLISH_PHRASE_FAKE : 'Chariot Progressive, listen. Mandelbrot set is in motion. Echo Choir has been breached',
  // Photo enrollment files
  PHOTO_ENROLLMENT_FILE_A_1 : 'test-data/faceA1.png',
  PHOTO_ENROLLMENT_FILE_B_1 : 'test-data/faceB1.jpg',
  PHOTO_ENROLLMENT_FILE_B_2 : 'test-data/faceB2.jpg',
  PHOTO_ENROLLMENT_FILE_B_3 : 'test-data/faceB3.jpg',
  PHOTO_ENROLLMENT_FILE_C_1 : 'test-data/faceC1.jpg',
  // Liveness attack files
  FALI_PHOTO_FILE_1 : 'test-data/fali_photo1.jpg',
  FALI_PHOTO_FILE_2 : 'test-data/fali_photo2.jpg',
  FALI_VIDEO_FILE : 'test-data/fali_video2.mp4',
  // Voice edge case files
  STTF_FILE : 'test-data/sttf.wav',
  SRNR_FILE : 'test-data/srnr.m4a',
  SSTL_FILE : 'test-data/sstl.wav',
  SSTQ_FILE : 'test-data/sstq.wav',
  NEHSD_FILE : 'test-data/nehsd.wav',
  PDNM_FILE : 'test-data/pdnm.wav',
  // Video edge case files
  FNFD_FILE : 'test-data/fnfd.mp4',
  FTMF_VIDEO_FILE : 'test-data/ftmf_video.mov',
  STTF_VIDEO_FILE : 'test-data/sttf_video.mov',
  PDNM_VIDEO_FILE : 'test-data/pdnm_video.mov',
  // Cross-modal test files
  ARMAAN_FACE_STEPHEN_VOICE : 'test-data/BFaceCVoice.mp4',
  ARMAAN_VOICE_STEPHEN_FACE : 'test-data/BVoiceCFace.mp4',
  // Fake/empty files
  FAKE_FILE : 'test-data/fake.wav',
  FAKE_VIDEO_FILE : 'test-data/fake.mp4',
  FAKE_PHOTO_FILE : 'test-data/fake.jpeg',
  EMPTY_FILE : 'test-data/empty.file',
  getURL:(filePath)=>{
    return `${TestConfig.VOICEIT_DRIVE_URL}${filePath.replace('test-data/', '')}`;
  }
}
module.exports = TestConfig;
